service: projects

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:eu-west-2:485681223941:*"
    - Effect: Allow
      Action:
        - cognito-idp:ListUsers
        - cognito-idp:AdminListGroupsForUser
        - cognito-idp:AdminRemoveUserFromGroup
        - cognito-idp:AdminAddUserToGroup
      Resource: "arn:aws:cognito-idp:eu-west-2:485681223941:*"
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "arn:aws:ses:eu-west-1:485681223941:*"
  environment:
    COGNITO_POOL: "eu-west-2_zVlfrxmDj"

functions:
  projects:
    handler: handler.projects
    name: ${self:provider.stage}-projectsHandler
    description: Handles API calls related to projects collection
    events:
      - http:
          path: projects
          method: post
          cors: true
          authorizer:
            arn:  arn:aws:cognito-idp:eu-west-2:485681223941:userpool/eu-west-2_zVlfrxmDj
      - http:
          path: projects
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:485681223941:userpool/eu-west-2_zVlfrxmDj
  project:
    handler: handler.project
    name: ${self:provider.stage}-projectHandler
    description: Handles API calls related to a project
    events:
      - http:
          path: projects/{uuid}
          method: delete
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:485681223941:userpool/eu-west-2_zVlfrxmDj
      - http:
          path: projects/{uuid}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:485681223941:userpool/eu-west-2_zVlfrxmDj
      - http:
          path: projects/{uuid}
          method: put
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:485681223941:userpool/eu-west-2_zVlfrxmDj
  projectDevelopers:
    handler: handler.projectDevelopers
    name: ${self:provider.stage}-projectDevelopersHandler
    descrition: Handles API calls related to developers on a project
    events:
      - http:
          path: projects/{uuid}/developers
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:485681223941:userpool/eu-west-2_zVlfrxmDj
      - http:
          path: projects/{uuid}/developers
          method: delete
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:485681223941:userpool/eu-west-2_zVlfrxmDj
  user:
    handler: handler.users
    name: ${self:provider.stage}-userHandler
    description: Handles API calls related to users
    events:
      - http:
          path: users
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:485681223941:userpool/eu-west-2_zVlfrxmDj
      - http:
          path: users/{sub}
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:485681223941:userpool/eu-west-2_zVlfrxmDj
      - http:
          path: users/{sub}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:485681223941:userpool/eu-west-2_zVlfrxmDj
  userGroups:
    handler: handler.userGroups
    name: ${self:provider.stage}-userGroupsHandler
    description: Handles API calls related to user groups
    events:
      - http:
          path: user_groups/{username}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:485681223941:userpool/eu-west-2_zVlfrxmDj
      - http:
          path: user_groups/{username}
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:485681223941:userpool/eu-west-2_zVlfrxmDj

resources:
  Resources:
    projectsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: projects
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: sub
            AttributeType: S
        KeySchema:
          - AttributeName: sub
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

package:
  exclude:
    - node_modules/**
